name: Build RISC-V Toolchain Multi-Lib Cross Compiler (baremetal)

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Run the RISC-V Toolchain build'
        required: true
        default: 'yes'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev

      - name: Build RISC-V Toolchain
        run: |
          git clone https://github.com/riscv/riscv-gnu-toolchain
          cd riscv-gnu-toolchain
          ./configure --prefix=/opt/riscv --enable-multilib
          make -j $(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: multilib-cc-baremetal
          path: /opt/riscv