name: Build RISC-V Toolchain

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Run the RISC-V Toolchain build'
        required: true
        default: 'yes'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev

      - name: Build RISC-V Toolchain
        run: |
          git clone https://github.com/riscv-software-src/riscv-isa-sim.git
          sudo pt-get install device-tree-compiler
          mkdir build
          cd build
          ../configure --prefix=$RISCV
          make -j16
          sudo make install
      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: riscv-toolchain
          path: /opt/riscv